const slug=new URLSearchParams(location.search).get('slug');const root=document.getElementById('article');
async function run(){
try{
 const r=await fetch('/api/blog/post/'+encodeURIComponent(slug||''));if(!r.ok)throw 0;
 const j=await r.json();const p=j.post;document.title=p.seoTitle||p.title;
 document.getElementById('desc').content=p.metaDescription||p.excerpt||'';document.getElementById('ogtitle').content=p.title;document.getElementById('ogdesc').content=p.excerpt||'';document.getElementById('canonical').href=location.origin+'/blog-article.html?slug='+encodeURIComponent(p.slug);
 const share=encodeURIComponent(location.href);
 const hubLinks='<div class="hub-cta"><strong>Explore CBE Nexus</strong><a href="/international-teaching-jobs.html">🌍 Teacher Jobs</a><a href="/scholarships-opportunities.html">🎓 Scholarships</a><a href="/professional-cv-writing.html">📄 Build Your CV</a><a href="/ai-training.html">🤖 AI Training</a><a href="/resource-category.html">📚 Teaching Resources</a></div>';
 root.innerHTML=`<div class="tag">${esc(p.category)}</div><h1>${esc(p.title)}</h1><p class="meta">By ${esc(p.author||'CBE Nexus')} · ${new Date(p.publishedAt).toLocaleDateString()}</p>${p.featuredImage?`<img src="${esc(p.featuredImage)}" alt="${esc(p.title)}">`:''}<div class="share"><a target="_blank" rel="noopener" href="https://wa.me/?text=${encodeURIComponent(p.title+' '+location.href)}">WhatsApp</a><a target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=${share}">Facebook</a><button type="button" id="copyLink">Copy link</button></div><div class="content">${p.content}</div>${hubLinks}<section class="related"><h2>More from the Education Hub</h2><div id="relatedPosts">Loading related articles...</div></section>`;
 const ld=document.createElement('script');ld.type='application/ld+json';ld.textContent=JSON.stringify({"@context":"https://schema.org","@type":"Article","headline":p.title,"description":p.metaDescription||p.excerpt||"","author":{"@type":"Organization","name":p.author||"CBE Nexus"},"publisher":{"@type":"Organization","name":"CBE Nexus"},"datePublished":p.publishedAt||p.createdAt,"dateModified":p.updatedAt||p.publishedAt||p.createdAt,"mainEntityOfPage":{"@type":"WebPage","@id":location.href},...(p.featuredImage?{"image":[new URL(p.featuredImage,location.origin).href]}:{})});document.head.appendChild(ld);
 document.getElementById('copyLink')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);document.getElementById('copyLink').textContent='Copied!';}catch{}});
 const all=(await (await fetch('/api/blog/posts')).json()).posts||[];const rel=all.filter(x=>x.slug!==p.slug&&(x.category===p.category||p.keywords&&x.keywords&&p.keywords.split(',').some(k=>x.keywords.toLowerCase().includes(k.trim().toLowerCase())))).slice(0,4);
 document.getElementById('relatedPosts').innerHTML=rel.length?rel.map(x=>`<a class="related-card" href="/blog-article.html?slug=${encodeURIComponent(x.slug)}"><strong>${esc(x.title)}</strong><small>${esc(x.category)}</small></a>`).join(''):'<p>Explore more guides on the <a href="/blog.html">Education Hub</a>.</p>';
}catch{root.innerHTML='<h1>Article not found</h1><p>Return to the <a href="/blog.html">CBE Nexus Education Hub</a>.</p>'}}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}run();