(function () {
  const allowed = [".pdf", ".doc", ".docx", ".ppt", ".pptx", ".xls", ".xlsx", ".txt", ".zip"];

  function json(key) { try { return JSON.parse(localStorage.getItem(key) || "[]"); } catch { return []; } }
  function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
  function safeFileName(name) { return String(name || "resource.bin").replace(/[^a-zA-Z0-9._-]+/g, "-"); }
  async function upload(file, meta) {
    const ext = "." + (file.name.split(".").pop() || "").toLowerCase();
    if (!allowed.includes(ext)) throw new Error("Unsupported file type.");
    const role = meta.role || "admin";
    const response = await fetch("/api/r2/upload", {credentials:"same-origin",method:"POST",headers:{"Content-Type":file.type||"application/octet-stream","X-CBE-Grade":String(meta.grade||""),"X-CBE-Subject":String(meta.subject||""),"X-CBE-Type":String(meta.type||""),"X-CBE-Filename":safeFileName(file.name),"X-CBE-Resource-Id":String(meta.resourceId||"resource"),"X-CBE-Role":role},body:file});
    const data=await response.json().catch(()=>({})); if(!response.ok||!data.ok) throw new Error(data.error||"Could not upload the resource to Cloudflare R2.");
    let previewKey=""; if(ext===".pdf"){try{const previewResponse=await fetch("/api/r2/prepare-preview",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:data.key})});const previewData=await previewResponse.json();if(previewResponse.ok&&previewData.ok&&previewData.previewKey)previewKey=previewData.previewKey;}catch{}}
    return {key:data.key,previewKey,fileName:file.name};
  }
  function stop(event){event.preventDefault();event.stopImmediatePropagation();}
  const resourceForm=document.querySelector("#resourceForm");
  if(resourceForm){resourceForm.addEventListener("submit",async function(event){stop(event);const status=document.querySelector("#formStatus"),file=document.querySelector("#fileInput").files[0];if(!file){status.textContent="Please choose a resource file before publishing.";return;}const id="admin-"+Date.now();status.textContent="Uploading resource to Cloudflare R2...";try{const grade=document.querySelector("#adminGradeInput").value.trim(),subject=document.querySelector("#adminSubjectInput").value.trim(),type=document.querySelector("#adminTypeInput").value.trim(),title=document.querySelector("#titleInput").value.trim()||file.name.replace(/\\.[^.]+$/,"");if(!grade||!subject||!type)throw new Error("Please select Grade, Subject, and Material Type before publishing.");const result=await upload(file,{grade,subject,type,resourceId:id,role:"admin"});const resource={id,title,grade,subject,type,description:document.querySelector("#descriptionInput").value.trim(),notes:document.querySelector("#notesContentInput").value.trim(),price:Number(document.querySelector("#priceInput").value||0),discount:Number(document.querySelector("#discountInput").value||0),term:document.querySelector("#termInput").value,isFreeSample:document.querySelector("#freeSampleInput").value==="true",popularity:1,fileName:result.fileName,r2Key:result.key,previewKey:result.previewKey,file:"/api/r2/file?key="+encodeURIComponent(result.key)};const existing=json("cbeResources"),saveResponse=await fetch("/api/resources",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({...resource,role:"admin",status:"approved"})}),saveData=await saveResponse.json();if(!saveResponse.ok||!saveData.ok)throw new Error(saveData.error||"Resource database save failed.");const savedResource=saveData.saved||resource;save("cbeResources",[...existing.filter(item=>item.id!==savedResource.id),savedResource]);status.textContent="Resource uploaded to Cloudflare R2 and saved to Supabase successfully.";resourceForm.reset();}catch(error){status.textContent=error.message||"R2 upload failed.";}},true);}
  const sellerForm=document.querySelector("#sellerForm");
  if(sellerForm){sellerForm.addEventListener("submit",async function(event){stop(event);const status=document.querySelector("#sellerStatus"),file=document.querySelector("#sellerFileInput").files[0];if(!file){status.textContent="Please choose a seller resource file.";return;}const id="seller-"+Date.now();status.textContent="Uploading seller resource to Cloudflare R2...";try{const grade=document.querySelector("#sellerGradeInput").value,subject=document.querySelector("#sellerSubjectInput").value,type=document.querySelector("#sellerTypeInput").value,result=await upload(file,{grade,subject,type,resourceId:id,role:"seller"}),item={id,sellerName:document.querySelector("#sellerNameInput").value.trim(),sellerPhone:document.querySelector("#sellerPhoneInput").value.trim(),title:document.querySelector("#sellerTitleInput").value.trim(),price:Number(document.querySelector("#sellerPriceInput").value||0),grade,subject,type,discount:Number(document.querySelector("#sellerDiscountInput").value||0),description:document.querySelector("#sellerDescriptionInput").value.trim(),fileName:result.fileName,fileSize:file.size,r2Key:result.key,previewKey:result.previewKey,file:"/api/r2/file?key="+encodeURIComponent(result.key),status:"pending",createdAt:new Date().toISOString()},activeSeller=JSON.parse(sessionStorage.getItem("activeSellerAccount")||"null"),saveResponse=await fetch("/api/resources",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({...item,role:"seller",sellerUsername:activeSeller?.username||"",status:"pending"})}),saveData=await saveResponse.json();if(!saveResponse.ok||!saveData.ok)throw new Error(saveData.error||"Seller resource database save failed.");const savedItem=saveData.saved||item;save("cbeSellerResources",[savedItem,...json("cbeSellerResources").filter(entry=>entry.id!==savedItem.id)]);status.textContent="Seller resource uploaded to R2 and saved to Supabase for approval.";sellerForm.reset();}catch(error){status.textContent=error.message||"R2 upload failed.";}},true);}
  const projectForm=document.querySelector("#projectUploadForm");
  if(projectForm){projectForm.addEventListener("submit",async function(event){stop(event);const status=document.querySelector("#projectStatus"),file=document.querySelector("#projectFileInput").files[0];if(!file){status.textContent="Please choose a project file.";return;}const id="project-"+Date.now();status.textContent="Uploading project to Cloudflare R2...";try{const grade=document.querySelector("#projectGradeInput").value,subject=document.querySelector("#projectSubjectInput").value.trim(),result=await upload(file,{grade,subject,type:"CBC Projects",resourceId:id,role:"project"}),project={id,title:document.querySelector("#projectTitleInput").value.trim(),grade,subject,notes:document.querySelector("#projectNotesInput").value.trim(),fileName:result.fileName,r2Key:result.key,file:"/api/r2/file?key="+encodeURIComponent(result.key),createdAt:new Date().toISOString()};save("cbeProjects",[project,...json("cbeProjects")]);status.textContent="Project uploaded successfully to Cloudflare R2.";projectForm.reset();}catch(error){status.textContent=error.message||"R2 upload failed.";}},true);}
  const adminButton=document.querySelector("#adminAreaButton");if(adminButton){adminButton.addEventListener("click",function(event){event.preventDefault();const login=document.querySelector("#adminLogin");if(!login)return;login.classList.add("open");login.setAttribute("aria-hidden","false");login.scrollIntoView({behavior:"smooth",block:"start"});},true);}

  /* Floating Customer Service — no API key required. */
  function initCustomerService(){
    if(document.getElementById("cbeCustomerFab"))return;
    const css=document.createElement("link");css.rel="stylesheet";css.href="/customer-service.css?v=20260929";document.head.appendChild(css);
    const waNumber="254798462815";
    const wa=(message)=>"https://wa.me/"+waNumber+"?text="+encodeURIComponent(message);
    const root=document.createElement("div");
    root.innerHTML=`<button id="cbeCustomerFab" class="cbe-customer-fab" type="button" aria-label="Open Customer Service"><span class="cbe-customer-fab-dot"></span>Customer Service</button><section id="cbeCustomerPanel" class="cbe-customer-panel" aria-hidden="true" aria-label="CBE Nexus Customer Service"><header class="cbe-customer-header"><div><strong>Customer Service</strong><small>CBE Nexus • Online support</small></div><button id="cbeCustomerClose" class="cbe-customer-close" type="button" aria-label="Close">×</button></header><div id="cbeCustomerMessages" class="cbe-customer-messages"></div><div class="cbe-customer-actions"><button type="button" data-customer-question="How do I pay?">💳 Payment</button><button type="button" data-customer-question="I want to buy a resource">🛒 Buy</button><button type="button" data-customer-question="What resources do you have?">📚 Resources</button><a id="cbeCustomerWhatsApp" class="cbe-customer-whatsapp" target="_blank" rel="noopener">💬 WhatsApp</a></div><form id="cbeCustomerForm" class="cbe-customer-form"><input id="cbeCustomerInput" autocomplete="off" placeholder="Ask Customer Service..." aria-label="Message"><button type="submit">Send</button></form></section>`;
    document.body.appendChild(root);
    const panel=document.getElementById("cbeCustomerPanel"),messages=document.getElementById("cbeCustomerMessages"),input=document.getElementById("cbeCustomerInput");
    const add=(html,who)=>{const m=document.createElement("div");m.className="cbe-customer-message "+who;m.innerHTML=html;messages.appendChild(m);messages.scrollTop=messages.scrollHeight;};
    const reply=(text)=>{const t=text.toLowerCase();if(/^(hi|hello|hey|habari|mambo|good morning|good afternoon|good evening)\b/.test(t))return`Hello! 👋 Welcome to CBE Nexus Customer Service. I can help you find resources, explain M-Pesa payment, or connect you to WhatsApp for a purchase.`;if(/pay|payment|lipa|mpesa|m-pesa|stk|price|cost/.test(t))return`💳 <strong>How to pay:</strong><br>1. Choose your resource.<br>2. Click <strong>Pay M-Pesa</strong>.<br>3. Enter your Safaricom number.<br>4. Approve the STK Push on your phone.<br>5. Follow the download instructions after successful payment.<br><br>If payment fails, use WhatsApp below.`;if(/whatsapp|buy|purchase|order|nunua|contact/.test(t))return`💬 You can purchase a resource or get payment assistance through WhatsApp. Click the WhatsApp button below and tell us the resource you want.`;if(/resource|notes|scheme|lesson|exam|paper|marking|material|book/.test(t))return`📚 CBE Nexus provides CBC/CBE notes, schemes of work, lesson plans, assessments, topical questions, past papers, marking schemes, study guides and other learning resources for Kenyan learners and teachers.`;return`I can help with <strong>payments</strong>, <strong>resources</strong>, or <strong>WhatsApp purchases</strong>. What would you like help with?`;};
    const open=()=>{panel.classList.add("open");panel.setAttribute("aria-hidden","false");setTimeout(()=>input.focus(),80)};const close=()=>{panel.classList.remove("open");panel.setAttribute("aria-hidden","true")};
    document.getElementById("cbeCustomerFab").addEventListener("click",open);document.getElementById("cbeCustomerClose").addEventListener("click",close);document.getElementById("cbeCustomerWhatsApp").href=wa("Hello CBE Nexus, I want to buy a resource and need assistance.");
    document.querySelectorAll("[data-customer-question]").forEach(b=>b.addEventListener("click",()=>{const q=b.dataset.customerQuestion;add(q,"user");setTimeout(()=>add(reply(q),"bot"),180)}));
    document.getElementById("cbeCustomerForm").addEventListener("submit",e=>{e.preventDefault();const q=input.value.trim();if(!q)return;add(q,"user");input.value="";setTimeout(()=>add(reply(q),"bot"),180)});
    add(`Hello! 👋 I'm <strong>Customer Service</strong>. How can I help you today?<br><br>Choose <strong>Payment</strong>, <strong>Buy</strong>, or <strong>WhatsApp</strong>.`,"bot");
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initCustomerService);else initCustomerService();
})();
