(function(){
const q=id=>document.getElementById(id);const form=q("adminOpportunityForm");if(!form)return;
async function load(){const r=await fetch("/api/admin/opportunities",{credentials:"same-origin",cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||"Could not load opportunities.");const rows=d.opportunities||[];q("adminOpportunityList").innerHTML=rows.length?rows.map(x=>'<div class="admin-management-item"><div><strong>'+esc(x.title)+'</strong><br><small>'+esc(x.type)+' · '+esc(x.country)+' · '+esc(x.status)+'</small></div><div><button class="secondary-button" type="button" data-edit-op="'+esc(x.id)+'">✏ Edit</button> <button class="ghost-button" type="button" data-del-op="'+esc(x.id)+'">Delete</button></div></div>').join(""):'<p>No opportunities added yet.</p>';q("adminOpportunitySummary").textContent=rows.length+" opportunities";}
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function fill(x){form.dataset.editId=x.id;["title","organization","country","level","field","funding","openingDate","deadline","applyUrl","description","eligibility","benefits","requirements"].forEach(k=>{const el=q("op"+k[0].toUpperCase()+k.slice(1)+"Input");if(el)el.value=x[k.replace("openingDate","opening_date").replace("applyUrl","apply_url")]||""});q("opTypeInput").value=x.type||"Scholarship";q("opStatusInput").value=x.status||"published";q("opFeaturedInput").checked=!!x.featured;q("saveOpportunityButton").textContent="💾 Update Opportunity";form.scrollIntoView({behavior:"smooth",block:"start"});}
form.addEventListener("submit",async e=>{e.preventDefault();q("adminOpportunityStatus").textContent="Saving…";const body={id:form.dataset.editId,title:q("opTitleInput").value,organization:q("opOrganizationInput").value,country:q("opCountryInput").value,type:q("opTypeInput").value,level:q("opLevelInput").value,field:q("opFieldInput").value,funding:q("opFundingInput").value,openingDate:q("opOpeningDateInput").value,deadline:q("opDeadlineInput").value,applyUrl:q("opApplyUrlInput").value,description:q("opDescriptionInput").value,eligibility:q("opEligibilityInput").value,benefits:q("opBenefitsInput").value,requirements:q("opRequirementsInput").value,status:q("opStatusInput").value,featured:q("opFeaturedInput").checked};try{const r=await fetch("/api/admin/opportunity",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||"Could not save.");q("adminOpportunityStatus").textContent="✓ Saved successfully.";form.reset();delete form.dataset.editId;q("saveOpportunityButton").textContent="➕ Publish Opportunity";load()}catch(e){q("adminOpportunityStatus").textContent=e.message}});
q("clearAdminOpportunityButton")?.addEventListener("click",()=>{form.reset();delete form.dataset.editId;q("saveOpportunityButton").textContent="➕ Publish Opportunity";q("adminOpportunityStatus").textContent=""});
q("adminOpportunityList")?.addEventListener("click",async e=>{const ed=e.target.closest("[data-edit-op]");if(ed){const r=await fetch("/api/admin/opportunities",{credentials:"same-origin"}),d=await r.json();fill((d.opportunities||[]).find(x=>String(x.id)===String(ed.dataset.editOp)));}const del=e.target.closest("[data-del-op]");if(del&&confirm("Delete this opportunity?")){const r=await fetch("/api/admin/opportunity-delete",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:del.dataset.delOp})});const d=await r.json();q("adminOpportunityStatus").textContent=d.ok?"✓ Deleted.":(d.error||"Delete failed.");load()}});
fetch("/api/admin/me",{credentials:"same-origin"}).then(r=>r.json()).then(d=>{if(!d.authenticated)form.closest(".admin-opportunities-card")?.remove();else load()}).catch(()=>form.closest(".admin-opportunities-card")?.remove());
window.CBENexusLoadOpportunitiesAdmin=load;
})();