(function(){
'use strict';
const p=(location.pathname||'').toLowerCase();
const pages=[
{match:['schools-institutions','school-directory'],name:'CBE Nexus Schools',tag:'SCHOOLS & INSTITUTIONS',color:'#e8f4ff',accent:'#1976a8',links:[['School Directory','school-directory.html'],['School Vacancies','school-directory.html'],['International Teaching Jobs','international-teaching-jobs.html'],['Teacher CV Builder','professional-cv-writing.html'],['Scholarships','scholarships-opportunities.html']]},
{match:['scholarships-opportunities'],name:'CBE Nexus Opportunities',tag:'SCHOLARSHIPS & OPPORTUNITIES',color:'#eef9e9',accent:'#2f7d32',links:[['Scholarships','scholarships-opportunities.html'],['Fully Funded Opportunities','scholarships-opportunities.html'],['Study Guides','blog.html'],['International Teaching Jobs','international-teaching-jobs.html'],['Career Guides','learning-hub.html']]},
{match:['resources','free-resources','lesson-planning-assessment'],name:'CBE Nexus Resources',tag:'TEACHING & LEARNING RESOURCES',color:'#fff3e4',accent:'#a85b18',links:[['Learning Resources','resources.html'],['Free Resources','free-resources.html'],['Lesson Planning','lesson-planning-assessment.html'],['Teaching with Technology','teaching-with-technology.html'],['AI for Teachers','ai-for-teachers.html']]},
{match:['professional-cv-writing'],name:'CBE Nexus Careers',tag:'PROFESSIONAL INTERNATIONAL TEACHER CV',color:'#eaf5ff',accent:'#1261a0',links:[['International Teacher Jobs','international-teaching-jobs.html'],['Teacher CV Builder','professional-cv-writing.html'],['Teaching Jobs UAE','international-teaching-jobs.html'],['Career Guides','learning-hub.html'],['Scholarships','scholarships-opportunities.html']]},
{match:['grade-10-school-finder'],name:'CBE Nexus Grade 10 Finder',tag:'GRADE 10 SCHOOL FINDER',color:'#fff4e8',accent:'#d26a16',links:[['Grade 10 School Finder','grade-10-school-finder.html'],['Schools & Institutions','schools-institutions.html'],['CBC Resources','resources.html'],['Education Hub','learning-hub.html'],['Career Guidance','learning-hub.html']]},
{match:['international-teaching-jobs'],name:'CBE Nexus Global Careers',tag:'INTERNATIONAL TEACHING JOBS',color:'#eaf4ff',accent:'#075985',links:[['Teaching Jobs Abroad','international-teaching-jobs.html'],['Teaching Jobs UAE','international-teaching-jobs.html'],['Teacher CV Builder','professional-cv-writing.html'],['School Vacancies','school-directory.html'],['Scholarships','scholarships-opportunities.html']]},
{match:['learning-hub','blog','blog-article'],name:'CBE Nexus Education Hub',tag:'EDUCATION HUB',color:'#e8f8f5',accent:'#0f766e',description:'Practical education news, teacher guides, career opportunities, scholarships, CBC/CBE insights, AI learning and professional development.',links:[['Latest Education Guides','blog.html'],['Teacher Career Guides','international-teaching-jobs.html'],['Scholarship Guides','scholarships-opportunities.html'],['Teacher CV Builder','professional-cv-writing.html'],['Free AI Training','ai-training.html'],['Teaching Resources','resources.html'],['School Directory','school-directory.html'],['Grade 10 Finder','grade-10-school-finder.html']]},
{match:['ai-training','ai-for-teachers','ai-for-students','generative-ai','chatgpt','gemini'],name:'CBE Nexus AI Academy',tag:'FREE AI TRAINING & DIGITAL SKILLS',color:'#f2ecff',accent:'#6d28d9',links:[['Free AI Training','ai-training.html'],['AI for Teachers','ai-for-teachers.html'],['AI for Students','ai-for-students.html'],['ChatGPT Mastery','chatgpt-mastery.html'],['Digital Skills','computer-digital-literacy.html']]}
];
const cfg=pages.find(x=>x.match.some(k=>p.includes(k)));if(!cfg)return;
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]));
const css=document.createElement('style');css.textContent=`.cbe-section-header{background:${cfg.color};border-bottom:3px solid ${cfg.accent};padding:12px 18px;position:relative;z-index:10;text-align:center!important}.cbe-section-header .inner,.cbe-section-footer .inner{max-width:1180px;margin:auto}.cbe-section-header .inner{text-align:center}.cbe-section-header .brand{display:flex;align-items:center;justify-content:center!important;gap:10px;flex-wrap:wrap;text-align:center!important}.cbe-section-header .brand strong{font-size:18px;color:#17384a}.cbe-section-header .section-intro{font-size:9px;line-height:1.4;color:#4b6470;margin:5px auto 0;max-width:850px}.cbe-section-header .tag{font-size:9px;font-weight:800;letter-spacing:.1em;color:${cfg.accent};padding:4px 7px;border-radius:999px;background:rgba(255,255,255,.65)}.cbe-section-header .section-intro{font-size:9px;line-height:1.4;color:#4b6470;margin-top:5px;max-width:850px}.cbe-section-header nav{display:flex;justify-content:center!important;align-items:center;gap:12px;flex-wrap:wrap;margin-top:8px;text-align:center!important}.cbe-section-header a{font-size:10px;color:#294b5e;text-decoration:none;font-weight:600}.cbe-section-header a:hover{color:${cfg.accent};text-decoration:underline}.cbe-section-footer{background:${cfg.color};border-top:4px solid ${cfg.accent};padding:24px 18px 12px;margin-top:28px;text-align:center!important}.cbe-section-footer .grid{display:grid;grid-template-columns:1fr;gap:16px;text-align:center}.cbe-section-footer h2{font-size:18px;color:#17384a;margin:3px 0 7px}.cbe-section-footer .kicker{font-size:9px;font-weight:800;letter-spacing:.1em;color:${cfg.accent}}.cbe-section-footer p{font-size:10px;line-height:1.55;color:#405766;margin:0 auto;max-width:760px}.cbe-section-footer .links{display:flex;justify-content:center!important;align-items:center;flex-wrap:wrap;gap:8px 16px;max-width:900px;margin:0 auto;text-align:center!important}.cbe-section-footer .links a{font-size:9px;color:#31576b;text-decoration:none}.cbe-section-footer .links a:hover{color:${cfg.accent};text-decoration:underline}.cbe-section-footer .seo{max-width:980px;margin:18px auto 8px;padding:12px;background:rgba(255,255,255,.65);border-radius:7px;font-size:8.5px;line-height:1.6;color:#405766;text-align:center}.cbe-section-footer .seo-links a{color:#31576b;text-decoration:none;margin-right:4px}.cbe-section-footer .seo-links a:hover{color:${cfg.accent};text-decoration:underline}.cbe-section-footer .seo-keywords{font-size:8px;color:#56717f}.cbe-section-footer .bottom{text-align:center;font-size:8px;color:#56717f;margin-top:12px}@media(max-width:700px){.cbe-section-header{padding:9px 10px}.cbe-section-header .brand strong{font-size:15px}.cbe-section-header nav{gap:8px}.cbe-section-header a{font-size:8px}.cbe-section-footer{padding:18px 10px 10px}.cbe-section-footer .grid{grid-template-columns:1fr;gap:14px}.cbe-section-footer .links{grid-template-columns:repeat(2,1fr)}.cbe-section-footer .links a{font-size:8px}}`;
document.head.appendChild(css);
const header=document.createElement('header');header.className='cbe-section-header';header.innerHTML='<div class="inner"><div class="brand"><strong>'+esc(cfg.name)+'</strong><span class="tag">'+esc(cfg.tag)+'</span></div><div class="section-intro">'+esc(cfg.description||'Connecting learners, teachers and education professionals with trusted learning and career information.')+'</div><nav aria-label="Section navigation">'+cfg.links.map(x=>'<a href="'+x[1]+'">'+esc(x[0])+'</a>').join('')+'</nav></div>';
const existingHeader=document.querySelector('body > header');if(existingHeader)existingHeader.replaceWith(header);else document.body.insertAdjacentElement('afterbegin',header);
const footer=document.createElement('footer');footer.className='cbe-section-footer';footer.innerHTML='<div class="inner"><div class="grid"><div><span class="kicker">'+esc(cfg.tag)+'</span><h2>'+esc(cfg.name)+'</h2><p>'+esc(cfg.description||'CBE Nexus connects learners, teachers, schools and education professionals with practical education resources, career opportunities, scholarships, professional tools and digital skills.')+'</p></div><nav class="links" aria-label="Section footer links">'+cfg.links.map(x=>'<a href="'+x[1]+'">'+esc(x[0])+'</a>').join('')+'</nav></div><div class="seo"><strong>Explore CBE Nexus:</strong> '+esc(cfg.tag.toLowerCase())+', '+esc(cfg.description||'Education guides, career opportunities, scholarships, teaching resources and digital learning.')+'<br><span class="seo-links">'+cfg.links.map(x=>'<a href="'+x[1]+'">'+esc(x[0])+'</a>').join(' · ')+'</span><br><span class="seo-keywords">Education Hub Kenya · CBC/CBE education · teacher career guides · teaching jobs abroad · scholarships · teacher CV builder · AI training · teaching resources</span></div><div class="bottom">&copy; 2026 CBE Nexus &middot; <a href="privacy-policy.html">Privacy</a> &middot; <a href="terms-and-conditions.html">Terms</a> &middot; Customer Care available on this page.</div></div>';

const oldFooter=document.querySelector('body > footer');if(oldFooter)oldFooter.replaceWith(footer);else document.body.appendChild(footer);
})();
