const http = require("http");
const fs = require("fs/promises");
const path = require("path");
const crypto = require("crypto");
const { createUploadUrl, createDownloadUrl, createPdfPreview } = require("./r2");
const OpenAI = require("openai");
const { supabase, supabaseConfigured } = require("./supabase");

const PORT = Number(process.env.PORT || 8000);
const ROOT = __dirname;
const DATA_DIR = path.join(ROOT, "backend-data");
const MAX_BODY_SIZE = 12 * 1024 * 1024;
const ADMIN_SESSION_TTL_MS = 8 * 60 * 60 * 1000;

function getAdminConfig() {
  return { username:String(process.env.ADMIN_USERNAME||"").trim(), email:String(process.env.ADMIN_EMAIL||"").trim().toLowerCase(), passwordHash:String(process.env.ADMIN_PASSWORD_HASH||""), sessionSecret:String(process.env.ADMIN_SESSION_SECRET||"") };
}
function safeEqual(a,b){const l=Buffer.from(String(a)),r=Buffer.from(String(b));return l.length===r.length&&crypto.timingSafeEqual(l,r);}
function verifyPassword(password,storedHash){return new Promise((resolve,reject)=>{const [salt,key]=String(storedHash).split(":");if(!salt||!key)return resolve(false);crypto.scrypt(String(password),salt,64,{N:16384,r:8,p:1},(e,k)=>e?reject(e):resolve(safeEqual(k.toString("hex"),key)));});}
function createAdminSession(){const c=getAdminConfig(),p=Buffer.from(JSON.stringify({u:c.username,exp:Date.now()+ADMIN_SESSION_TTL_MS})).toString("base64url"),s=crypto.createHmac("sha256",c.sessionSecret).update(p).digest("base64url");return p+"."+s;}
function verifyAdminSession(req){const c=getAdminConfig();if(!c.sessionSecret)return false;const m=String(req.headers.cookie||"").match(/(?:^|;\s*)cbe_admin_session=([^;]+)/);if(!m)return false;const [p,s]=decodeURIComponent(m[1]).split(".");if(!p||!s)return false;if(!safeEqual(s,crypto.createHmac("sha256",c.sessionSecret).update(p).digest("base64url")))return false;try{const d=JSON.parse(Buffer.from(p,"base64url").toString("utf8"));return d.u===c.username&&Number(d.exp)>Date.now();}catch{return false;}}
function adminCookie(t){return `cbe_admin_session=${encodeURIComponent(t)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=28800`;}
const SELLER_SESSION_TTL_MS=8*60*60*1000;
async function hashPassword(password){const salt=crypto.randomBytes(16).toString("hex");const key=await new Promise((res,rej)=>crypto.scrypt(String(password),salt,64,{N:16384,r:8,p:1},(e,k)=>e?rej(e):res(k.toString("hex"))));return salt+":"+key;}
function createSellerSession(username){const p=Buffer.from(JSON.stringify({u:username,exp:Date.now()+SELLER_SESSION_TTL_MS})).toString("base64url"),s=crypto.createHmac("sha256",String(process.env.ADMIN_SESSION_SECRET||"")).update("seller:"+p).digest("base64url");return p+"."+s;}
function verifySellerSession(req){const secret=String(process.env.ADMIN_SESSION_SECRET||"");if(!secret)return null;const m=String(req.headers.cookie||"").match(/(?:^|;\s*)cbe_seller_session=([^;]+)/);if(!m)return null;const [p,s]=decodeURIComponent(m[1]).split("."),e=crypto.createHmac("sha256",secret).update("seller:"+p).digest("base64url");if(!p||!s||!safeEqual(s,e))return null;try{const d=JSON.parse(Buffer.from(p,"base64url").toString("utf8"));return Number(d.exp)>Date.now()?d.u:null;}catch{return null;}}
function sellerCookie(t){return `cbe_seller_session=${encodeURIComponent(t)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=28800`;}
const mimeTypes={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".gif":"image/gif",".svg":"image/svg+xml",".webp":"image/webp",".ico":"image/x-icon",".txt":"text/plain; charset=utf-8",".xml":"application/xml; charset=utf-8"};
const stores={"/api/projects":"projects.json","/api/tuition":"tuition-registrations.json","/api/quizzes":"quiz-attempts.json","/api/payments":"payments.json","/api/mpesa/stk-push":"mpesa-requests.json"};
async function ensureDataDir(){await fs.mkdir(DATA_DIR,{recursive:true});}
async function readJsonStore(f){await ensureDataDir();try{return JSON.parse(await fs.readFile(path.join(DATA_DIR,f),"utf8"));}catch{return [];}}
async function appendJsonStore(f,item){const c=await readJsonStore(f),s={id:item.id||`${Date.now()}`,...item,receivedAt:new Date().toISOString()};c.unshift(s);await fs.writeFile(path.join(DATA_DIR,f),JSON.stringify(c,null,2));return s;}
// Matches the actual Supabase resources table. preview_text is intentionally omitted because it is not present in the live schema.
function resourceRowFromPayload(p,sellerId=null){return {seller_id:sellerId,title:String(p.title||"").trim(),description:String(p.description||"").trim(),grade:String(p.grade||"").trim(),subject:String(p.subject||"").trim(),resource_type:String(p.type||"").trim(),filename:String(p.fileName||"").trim(),r2_key:String(p.r2Key||"").trim(),price:Math.max(0,Number(p.price||0)),discount_price:Math.max(0,Number(p.discountPrice||0)),status:String(p.status||"pending")};}
function resourcePayloadFromRow(r){return {id:r.id,title:r.title,grade:r.grade,subject:r.subject,type:r.resource_type||"",description:r.description||"",price:Number(r.price||0),discount:Number(r.discount_price||0),term:"",isFreeSample:false,popularity:0,fileName:r.filename||"",r2Key:r.r2_key||"",previewKey:"",previewText:"",file:r.r2_key?"/api/r2/file?key="+encodeURIComponent(r.r2_key):"",status:r.status||"pending",downloads:0,purchases:0,sellerId:r.seller_id||null,createdAt:r.created_at||null,updatedAt:r.updated_at||null};}
function sendJson(res,status,data){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8"});res.end(JSON.stringify(data));}
function readBody(req){return new Promise((resolve,reject)=>{let b="";req.on("data",c=>{b+=c;if(b.length>MAX_BODY_SIZE){reject(new Error("Request body too large."));req.destroy();}});req.on("end",()=>resolve(b));req.on("error",reject);});}
async function getMpesaAccessToken(){const k=String(process.env.MPESA_CONSUMER_KEY||""),s=String(process.env.MPESA_CONSUMER_SECRET||"");if(!k||!s)throw new Error("M-Pesa consumer credentials are not configured.");const base=String(process.env.MPESA_ENVIRONMENT||"sandbox").toLowerCase()==="production"?"https://api.safaricom.co.ke":"https://sandbox.safaricom.co.ke";return await new Promise((res,rej)=>{const https=require("https"),q=https.request(base+"/oauth/v1/generate?grant_type=client_credentials",{headers:{Authorization:"Basic "+Buffer.from(k+":"+s).toString("base64")}},r=>{let d="";r.on("data",c=>d+=c);r.on("end",()=>{try{const x=JSON.parse(d);x.access_token?res(x.access_token):rej(new Error("Daraja authorization failed."));}catch{rej(new Error("Invalid Daraja authorization response."));}})});q.on("error",rej);q.end();});}
function normalizeMpesaPhone(p){p=String(p||"").replace(/\s+/g,"");if(/^0[17]\d{8}$/.test(p))return"254"+p.slice(1);if(/^254[17]\d{8}$/.test(p))return p;return"";}
async function darajaPost(pathname,body,token){const https=require("https"),base=String(process.env.MPESA_ENVIRONMENT||"sandbox").toLowerCase()==="production"?"https://api.safaricom.co.ke":"https://sandbox.safaricom.co.ke";return await new Promise((res,rej)=>{const q=https.request(base+pathname,{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"}},r=>{let d="";r.on("data",c=>d+=c);r.on("end",()=>{try{res({status:r.statusCode||500,data:JSON.parse(d)});}catch{res({status:r.statusCode||500,data:{raw:d}});}})});q.on("error",rej);q.write(JSON.stringify(body));q.end();});}
async function generateAIHomeworkAnswer(p){if(!process.env.OPENAI_API_KEY)return null;const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model:process.env.OPENAI_HOMEWORK_MODEL||"gpt-5.6-luna",instructions:"You are the CBE Nexus AI Homework Helper. Help learners understand and solve homework rather than giving unexplained answers. Use clear age-appropriate language, show steps and working for Mathematics and Science, explain reasoning for other subjects, do not invent facts, and ask for clarification when a question is unclear.",input:"Grade: "+String(p.grade||"CBC")+"\nSubject: "+String(p.subject||"General")+"\nHomework question: "+String(p.question||"")});return response.output_text||null;}

async function handleApi(req,res,url){
  if(req.method==="GET"&&url.pathname==="/api/admin/dashboard"){if(!verifyAdminSession(req)){sendJson(res,401,{ok:false,error:"Admin login required."});return true;}const [resources,localSellerAccounts,payments,mpesaRequests,tuition,localUsers]=await Promise.all([readJsonStore("resources.json"),readJsonStore("seller-accounts.json"),readJsonStore("payments.json"),readJsonStore("mpesa-requests.json"),readJsonStore("tuition-registrations.json"),readJsonStore("admin-users.json")]);let sellerAccounts=localSellerAccounts,users=localUsers;if(supabaseConfigured){try{const [{data:sellersData,error:sellersError},{data:usersData,error:usersError}]=await Promise.all([supabase.from("sellers").select("id,user_id,phone,username,status,created_at"),supabase.from("users").select("id,name,phone,role,status,created_at")]);if(sellersError)throw sellersError;if(usersError)throw usersError;sellerAccounts=sellersData||[];users=usersData||[];}catch(error){console.error("Supabase admin dashboard lookup error:",error);}}const userMap=new Map();[...users].forEach(u=>userMap.set(u.phone||u.username||u.id,u));[...payments,...mpesaRequests,...tuition].forEach(item=>{const phone=item.customerPhone||item.phone;if(phone&&!userMap.has(phone))userMap.set(phone,{id:"user-"+phone,name:item.learner||item.name||"Customer",phone,status:"active",source:"transaction"});});const allUsers=[...userMap.values()],sales=payments.filter(p=>["paid","completed","success"].includes(String(p.status||"").toLowerCase())),totalDownloads=resources.reduce((s,r)=>s+Number(r.downloads||0),0),popularResources=[...resources].map(r=>({...r,downloads:Number(r.downloads||0),purchases:Number(r.purchases||0)})).sort((a,b)=>(b.downloads+b.purchases*3)-(a.downloads+a.purchases*3)).slice(0,10);sendJson(res,200,{ok:true,stats:{sellers:sellerAccounts.length,pendingSellers:sellerAccounts.filter(x=>x.status==="pending").length,resources:resources.length,pendingResources:resources.filter(x=>x.status==="pending").length,users:allUsers.length,sales:sales.length,purchases:sales.length,revenue:sales.reduce((s,x)=>s+Number(x.amount||0),0),downloads:totalDownloads},popularResources,sellers:sellerAccounts,resources,users:allUsers,sales,payments:[...payments,...mpesaRequests].slice(0,100)});return true;}
  if(req.method==="POST"&&url.pathname==="/api/admin/resource"){if(!verifyAdminSession(req)){sendJson(res,401,{ok:false,error:"Admin login required."});return true;}const p=JSON.parse((await readBody(req))||"{}"),items=await readJsonStore("resources.json"),item={...p,status:p.status||"approved",updatedAt:new Date().toISOString()};await fs.writeFile(path.join(DATA_DIR,"resources.json"),JSON.stringify([item,...items.filter(x=>x.id!==item.id)],null,2));sendJson(res,200,{ok:true,resource:item});return true;}
  if(req.method==="POST"&&url.pathname==="/api/admin/resource-status"){if(!verifyAdminSession(req)){sendJson(res,401,{ok:false,error:"Admin login required."});return true;}const p=JSON.parse((await readBody(req))||"{}"),items=await readJsonStore("resources.json"),next=items.map(x=>x.id===p.resourceId?{...x,status:String(p.status||"pending"),reviewedAt:new Date().toISOString()}:x);await fs.writeFile(path.join(DATA_DIR,"resources.json"),JSON.stringify(next,null,2));sendJson(res,200,{ok:true});return true;}
  if(req.method==="POST"&&url.pathname==="/api/admin/resource-price"){if(!verifyAdminSession(req)){sendJson(res,401,{ok:false,error:"Admin login required."});return true;}const p=JSON.parse((await readBody(req))||"{}"),items=await readJsonStore("resources.json"),next=items.map(x=>x.id===p.resourceId?{...x,price:Math.max(0,Number(p.price||0)),discount:Math.min(100,Math.max(0,Number(p.discount||0))),updatedAt:new Date().toISOString()}:x);await fs.writeFile(path.join(DATA_DIR,"resources.json"),JSON.stringify(next,null,2));sendJson(res,200,{ok:true});return true;}
  if(req.method==="POST"&&url.pathname==="/api/admin/user-status"){if(!verifyAdminSession(req)){sendJson(res,401,{ok:false,error:"Admin login required."});return true;}const p=JSON.parse((await readBody(req))||"{}"),status=String(p.status||"active");if(supabaseConfigured){try{let q=supabase.from("users").update({status}).select("id,name,phone,role,status").limit(1);if(p.userId)q=q.eq("id",p.userId);else if(p.phone)q=q.eq("phone",p.phone);else{sendJson(res,400,{ok:false,error:"User ID or phone is required."});return true;}const {data,error}=await q.single();if(error)throw error;sendJson(res,200,{ok:true,user:data,storage:"supabase"});return true;}catch(error){console.error("Supabase user status error:",error);sendJson(res,500,{ok:false,error:"User status could not be updated in Supabase."});return true;}}const users=await readJsonStore("admin-users.json"),existing=users.find(x=>x.id===p.userId||x.phone===p.phone),item={...(existing||{}),id:p.userId||existing?.id||"user-"+Date.now(),phone:p.phone||existing?.phone||"",name:p.name||existing?.name||"Customer",status,updatedAt:new Date().toISOString()};await fs.writeFile(path.join(DATA_DIR,"admin-users.json"),JSON.stringify([item,...users.filter(x=>x.id!==item.id&&x.phone!==item.phone)],null,2));sendJson(res,200,{ok:true,user:item,storage:"local"});return true;}
  if(req.method==="POST"&&url.pathname==="/api/admin/login"){const c=getAdminConfig();if(!c.username||!c.email||!c.passwordHash||!c.sessionSecret){sendJson(res,503,{ok:false,error:"Admin authentication is not configured on the server."});return true;}const p=JSON.parse((await readBody(req))||"{}"),u=String(p.username||"").trim(),e=String(p.email||"").trim().toLowerCase(),pw=String(p.password||""),valid=safeEqual(u.toUpperCase(),c.username.toUpperCase())&&safeEqual(e,c.email)&&await verifyPassword(pw,c.passwordHash);if(!valid){sendJson(res,401,{ok:false,error:"Invalid admin username, password, or email."});return true;}res.setHeader("Set-Cookie",adminCookie(createAdminSession()));sendJson(res,200,{ok:true,user:{username:c.username,email:c.email}});return true;}
  if(req.method==="GET"&&url.pathname==="/api/admin/me"){if(!verifyAdminSession(req)){sendJson(res,401,{ok:false,authenticated:false});return true;}const c=getAdminConfig();sendJson(res,200,{ok:true,authenticated:true,user:{username:c.username,email:c.email}});return true;}
  if(req.method==="POST"&&url.pathname==="/api/admin/logout"){res.setHeader("Set-Cookie","cbe_admin_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0");sendJson(res,200,{ok:true});return true;}
  if(req.method==="POST"&&url.pathname==="/api/seller/account"){const p=JSON.parse((await readBody(req))||"{}"),u=String(p.username||"").trim().toLowerCase(),pw=String(p.password||""),name=String(p.name||"").trim(),phone=String(p.phone||"").trim();if(!u||pw.length<8||!name||!phone){sendJson(res,400,{ok:false,error:"Name, phone, username and a password of at least 8 characters are required."});return true;}if(supabaseConfigured){try{const {data:existing,error:existingError}=await supabase.from("sellers").select("id,username").eq("username",u).maybeSingle();if(existingError)throw existingError;if(existing){sendJson(res,409,{ok:false,error:"This seller username is already registered."});return true;}const passwordHash=await hashPassword(pw);const {data:user,error:userError}=await supabase.from("users").insert({name,phone,role:"seller",status:"active"}).select("id").single();if(userError)throw userError;const {data:seller,error:sellerError}=await supabase.from("sellers").insert({user_id:user.id,name,phone,username:u,password_hash:passwordHash,status:"pending"}).select("id,phone,username,status").single();if(sellerError)throw sellerError;sendJson(res,201,{ok:true,account:{...seller,name},storage:"supabase"});return true;}catch(error){console.error("Supabase seller registration error:",error);sendJson(res,500,{ok:false,error:"Seller account could not be created in Supabase."});return true;}}const ac=await readJsonStore("seller-accounts.json");if(ac.some(x=>x.username===u)){sendJson(res,409,{ok:false,error:"This seller username is already registered."});return true;}const a={id:"seller-account-"+Date.now(),name,phone,username:u,passwordHash:await hashPassword(pw),status:"pending",createdAt:new Date().toISOString()};await appendJsonStore("seller-accounts.json",a);sendJson(res,201,{ok:true,account:{id:a.id,name,phone,username:u,status:"pending"},storage:"local"});return true;}
  if(req.method==="POST"&&url.pathname==="/api/seller/login"){const p=JSON.parse((await readBody(req))||"{}"),u=String(p.username||"").trim().toLowerCase();let a=null;if(supabaseConfigured){try{const {data,error}=await supabase.from("sellers").select("id,user_id,phone,username,password_hash,status").eq("username",u).maybeSingle();if(error)throw error;a=data;}catch(error){console.error("Supabase seller login lookup error:",error);sendJson(res,500,{ok:false,error:"Seller account could not be checked in Supabase."});return true;}}else{const ac=await readJsonStore("seller-accounts.json");a=ac.find(x=>x.username===u);}if(!a||!(await verifyPassword(String(p.password||""),a.password_hash||a.passwordHash||""))){sendJson(res,401,{ok:false,error:"Invalid seller username or password."});return true;}if(a.status!=="approved"){sendJson(res,403,{ok:false,error:"Seller account is pending admin approval."});return true;}res.setHeader("Set-Cookie",sellerCookie(createSellerSession(u)));sendJson(res,200,{ok:true,account:{id:a.id,name:a.name||"Seller",phone:a.phone,username:a.username,status:a.status},storage:supabaseConfigured?"supabase":"local"});return true;}
  if(req.method==="POST"&&url.pathname==="/api/admin/seller-resource-status"){if(!verifyAdminSession(req)){sendJson(res,401,{ok:false,error:"Admin login required."});return true;}const p=JSON.parse((await readBody(req))||"{}"),items=await readJsonStore("resources.json"),next=items.map(x=>x.id===p.resourceId?{...x,status:String(p.status||"pending"),reviewedAt:new Date().toISOString()}:x);await fs.writeFile(path.join(DATA_DIR,"resources.json"),JSON.stringify(next,null,2));sendJson(res,200,{ok:true});return true;}
  if(req.method==="POST"&&url.pathname==="/api/admin/seller-account-status"){if(!verifyAdminSession(req)){sendJson(res,401,{ok:false,error:"Admin login required."});return true;}const p=JSON.parse((await readBody(req))||"{}"),status=String(p.status||"pending");if(supabaseConfigured){try{const {data,error}=await supabase.from("sellers").update({status}).eq("id",p.accountId).select("id,phone,username,status").single();if(error)throw error;sendJson(res,200,{ok:true,account:data,storage:"supabase"});return true;}catch(error){console.error("Supabase seller approval error:",error);sendJson(res,500,{ok:false,error:"Seller status could not be updated in Supabase."});return true;}}const ac=await readJsonStore("seller-accounts.json"),up=ac.map(x=>x.id===p.accountId?{...x,status,reviewedAt:new Date().toISOString()}:x);await fs.writeFile(path.join(DATA_DIR,"seller-accounts.json"),JSON.stringify(up,null,2));sendJson(res,200,{ok:true,storage:"local"});return true;}
  if(req.method==="POST"&&url.pathname==="/api/r2/upload-url"){const p=JSON.parse((await readBody(req))||"{}"),admin=verifyAdminSession(req),seller=verifySellerSession(req);if(p.role==="admin"&&!admin){sendJson(res,401,{ok:false,error:"Admin login required."});return true;}if(p.role==="seller"&&!seller){sendJson(res,401,{ok:false,error:"Approved seller login required."});return true;}if(!["admin","seller"].includes(p.role)){sendJson(res,400,{ok:false,error:"Upload role is required."});return true;}sendJson(res,200,{ok:true,...await createUploadUrl(p)});return true;}
  if(req.method==="POST"&&url.pathname==="/api/r2/project-upload-url"){const p=JSON.parse((await readBody(req))||"{}");if(!p.grade||!p.subject){sendJson(res,400,{ok:false,error:"Project grade and subject are required."});return true;}sendJson(res,200,{ok:true,...await createUploadUrl({...p,type:"CBC Projects"})});return true;}
  if(req.method==="GET"&&url.pathname==="/api/supabase/status"){sendJson(res,200,{ok:supabaseConfigured,supabaseConfigured,message:supabaseConfigured?"Supabase connection is configured.":"Add SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY to the Render environment."});return true;}
  if(req.method==="GET"&&url.pathname==="/api/r2/status"){const required=["R2_ACCOUNT_ID","R2_ACCESS_KEY_ID","R2_SECRET_ACCESS_KEY","R2_BUCKET_NAME"],missing=required.filter(n=>!process.env[n]);sendJson(res,200,{ok:missing.length===0,r2Configured:missing.length===0,missing});return true;}
  if(req.method==="GET"&&url.pathname==="/api/resources"){if(supabaseConfigured){try{const {data,error}=await supabase.from("resources").select("*").order("created_at",{ascending:false});if(error)throw error;sendJson(res,200,{ok:true,resources:(data||[]).map(resourcePayloadFromRow),storage:"supabase"});return true;}catch(error){console.error("Supabase resource lookup error:",error);sendJson(res,500,{ok:false,error:"Resources could not be loaded from Supabase."});return true;}}sendJson(res,200,{ok:true,resources:await readJsonStore("resources.json"),storage:"local"});return true;}
  if(req.method==="POST"&&url.pathname==="/api/resources"){const payload=JSON.parse((await readBody(req))||"{}"),isAdmin=verifyAdminSession(req),sellerUsername=String(payload.sellerUsername||"").trim().toLowerCase(),authenticatedSeller=verifySellerSession(req),isSeller=Boolean(authenticatedSeller);if((payload.role==="admin"&&!isAdmin)||(payload.role==="seller"&&!isSeller)){sendJson(res,401,{ok:false,error:"Authorized account required."});return true;}if(!["admin","seller"].includes(payload.role)){sendJson(res,400,{ok:false,error:"Resource role is required."});return true;}if(supabaseConfigured){try{let sellerId=null;if(payload.role==="seller"){const username=authenticatedSeller||sellerUsername,{data:seller,error:sellerError}=await supabase.from("sellers").select("id").eq("username",username).maybeSingle();if(sellerError)throw sellerError;if(!seller){sendJson(res,403,{ok:false,error:"Approved seller account was not found in Supabase."});return true;}sellerId=seller.id;}const row=resourceRowFromPayload(payload,sellerId);if(!row.title||!row.grade||!row.subject||!row.resource_type||!row.r2_key){sendJson(res,400,{ok:false,error:"Resource title, grade, subject, type and R2 file are required."});return true;}const {data,error}=await supabase.from("resources").insert(row).select("*").single();if(error)throw error;sendJson(res,201,{ok:true,saved:resourcePayloadFromRow(data),storage:"supabase"});return true;}catch(error){console.error("Supabase resource save error:",error);sendJson(res,500,{ok:false,error:"Resource could not be saved to Supabase."});return true;}}const saved=await appendJsonStore("resources.json",payload);sendJson(res,201,{ok:true,saved,storage:"local"});return true;}
  if(req.method==="POST"&&stores[url.pathname]){const p=JSON.parse((await readBody(req))||"{}");sendJson(res,201,{ok:true,saved:await appendJsonStore(stores[url.pathname],p)});return true;}
  if(req.method==="POST"&&url.pathname==="/api/homework-helper"){const p=JSON.parse((await readBody(req))||"{}");if(!String(p.question||"").trim()){sendJson(res,400,{ok:false,error:"Homework question is required."});return true;}try{const answer=await generateAIHomeworkAnswer(p);if(!answer){sendJson(res,503,{ok:false,configured:false,error:"AI Homework Helper is not configured yet. Add OPENAI_API_KEY to Render."});return true;}await appendJsonStore("homework-helper.json",{grade:p.grade,subject:p.subject,question:p.question,answer});sendJson(res,200,{ok:true,configured:true,answer});}catch(error){console.error("AI Homework Helper error:",error);sendJson(res,502,{ok:false,error:"The AI Homework Helper could not generate a response right now."});}return true;}
  if(url.pathname.startsWith("/api/")){sendJson(res,404,{ok:false,error:"API route not found."});return true;}return false;
}
async function serveStatic(req,res,url){const requestedPath=decodeURIComponent(url.pathname==="/"?"/index.html":url.pathname),filePath=path.resolve(ROOT,`.${requestedPath}`);if(!filePath.startsWith(ROOT)){res.writeHead(403,{"Content-Type":"text/plain; charset=utf-8"});res.end("Forbidden");return;}try{const stat=await fs.stat(filePath),target=stat.isDirectory()?path.join(filePath,"index.html"):filePath,data=await fs.readFile(target);res.writeHead(200,{"Content-Type":mimeTypes[path.extname(target).toLowerCase()]||"application/octet-stream"});res.end(data);}catch{res.writeHead(404,{"Content-Type":"text/plain; charset=utf-8"});res.end("Not found");}}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||"127.0.0.1"}`);try{if(await handleApi(req,res,url))return;await serveStatic(req,res,url);}catch(error){console.error("Unhandled server error:",error);sendJson(res,500,{ok:false,error:error.message||"Server error."});}});
server.listen(PORT,"0.0.0.0",()=>console.log(`CBE website backend running on port ${PORT}`));
