-- CBE Nexus resource-update email subscriptions
-- Run once in the Supabase SQL Editor for the project connected to Render.
create table if not exists public.resource_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  name text,
  source text not null default '/',
  consent boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists resource_subscribers_email_uidx
  on public.resource_subscribers (email);
alter table public.resource_subscribers enable row level security;
revoke all on table public.resource_subscribers from anon, authenticated;
